name: Teste Container
on:
    workflow_dispatch: 
jobs:
    build-test:
        runs-on: ubuntu-latest
        # container: 
        #     image: python:3.10.14-alpine3.20
        steps:
            - name: Execução do Runner
              run: cat /etc/os-release
            - name: Execução no Container
              uses: docker://alpine:latest
              with:
                entrypoint: cat
                args: /etc/os-release
            # - - - - - - - - - - - - - - - - - - - 
            # - name: Checkout
            #   uses: actions/checkout@v4
            # - name: Verifica a versão do python
            #   run: python3 --version
            # - name: Instalação curl Alpine
            #   run: apk add curl 
            # - name: Executando o curl
            #   run: curl https://www.google.com 
            # - - - - - - - - - - - - - - - - - - - 
